### ISSUE TITLE
Fatal Error: Cannot throw objects that do not implement Throwable

### ISSUE THREAD

**Issue by skunkbad** [seb86/cart-rest-api-for-woocommerce#35]
Since WP_Error does not extend Exception, and is not implementing Throwable, then when you do:

throw new WP_Error()

it results in a fatal error, and the error messages never get sent back in the request.

Instead, you should probably be doing something else, maybe just:

return new WP_Error()

This is for all the instances of "throw new WP_Error" that are found in the plugin.

**Comment by seb86** [comment]
@skunkbad  The add to cart function in this REST API was copied as is from the core of WC at the time of the initial development with only a small tweak for an action hook so I guess the error needs to be fixed in WC too if it has not already.

You are welcome to submit a pull request to fix this and you will get credit for your contribution.

**Comment by seb86** [comment]
Pull request #36
